Fix AppVeyor
MSVC complains about auto* here:

error: variable 'adjacent_iterator' with type 'auto *' has incompatible initializer of type 'std::_Array_iterator<int, 6>'
        auto* adjacent_iterator =
              ^

Change sonarcloud.yml to use gcc-11 just like codecov, due to the gcov database incompatibility with gcc.

Update the vcpkgGitCommitId in workflows to "962e5e39f8a25f42522f51fffc574e05a3efd26b".